{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "name": "EstudodeCaso-R.r",
      "provenance": [],
      "authorship_tag": "ABX9TyMwp3XJIBA8tdhDuNrGLrnJ",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/Felipe0042/DataScienceAcademy/blob/main/EstudodeCaso_R.r\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "LoNlN6KsT92d"
      },
      "source": [
        "# abrindo um dataset\n",
        "dataset_bank <- read.table(\"bank.csv\", header=TRUE,sep=\";\")\n",
        "View(dataset_bank)\n",
        "\n",
        "#Primeiro passo - Criando uma nova coluna de dados \n",
        "\n",
        "#acessando valores de uma tabela\n",
        "table(dataset_bank$job)\n",
        "#outra forma\n",
        "table(dataset_bank[[2]])\n",
        "\n",
        "library(dplyr)\n",
        "library(ggplot2)\n",
        "\n",
        "# - %>% -> pipe (função infixa)\n",
        "# tem como função facilitar a visualização da função\n",
        "# tem como finalidade tambem ajudar a programar pipelines\n",
        "\n",
        "#criando grafico de barras dos empregos no banco \n",
        "dataset_bank %>%\n",
        "  group_by(job) %>%\n",
        "  summarise(n=n()) %>%\n",
        "  ggplot(aes(x=job, y=n)) +\n",
        "  geom_bar(stat ='identity') +\n",
        "  theme(axis.text.x = element_text(angle=90, hjust = 1))\n",
        "\n",
        "\n",
        "#criando uma coluna no dataset definindo o nivel dos profissionais em termos\n",
        "#de uso de tecnologia\n",
        "\n",
        "\n",
        "#mutate - adicionar mais uma coluna ao seu banco de dados\n",
        "help(mutate)\n",
        "dataset_bank <- dataset_bank %>%\n",
        "  mutate(technology_use =\n",
        "           case_when(\n",
        "             job == 'admin'         ~ 'medio',\n",
        "             job == 'blue-collar'   ~ 'baixo',\n",
        "             job == 'entrepreneur'  ~ 'alto',\n",
        "             job == 'housemaid'     ~ 'baixo',\n",
        "             job == 'management'    ~ 'medio',\n",
        "             job == 'retired'       ~ 'baixo',\n",
        "             job == 'self-employed' ~ 'medio',\n",
        "             job == 'services'      ~ 'baixo',\n",
        "             job == 'student'       ~ 'alto',\n",
        "             job == 'technician'    ~ 'alto',\n",
        "             job == 'unemployed'    ~ 'baixo',\n",
        "             job == 'unknow'        ~ 'baixo',\n",
        "           ))\n",
        "\n",
        "View(dataset_bank)\n",
        "\n",
        "#visualizar conteudo da tabela\n",
        "qtd <-table(dataset_bank$technology_use)\n",
        "\n",
        "#em porcentual\n",
        "round(prop.table(qtd),2)\n",
        "\n",
        "#criando uma variavel dummy \n",
        "\n",
        "dataset_bank <- dataset_bank %>% \n",
        "  mutate(defaulted = ifelse(default == 'yes',1,0))\n",
        "\n",
        "\n",
        "#técnica One Hot Encoding\n",
        "#converter valor de uma variável categórica para um correspondente numérico\n",
        "\n",
        "library(caret)\n",
        "#criando variaveis dummy para todas do conjunto de dados indicado pelo \"~.\"\n",
        "dmy <- dummyVars(\"~.\", data=dataset_bank)\n",
        "\n",
        "#pego a função dmy e aplico ao meu conjuto de dados e por fim crio um novo dataframe \n",
        "bank.dummies <- data.frame(predict(dmy, newdata = dataset_bank))\n",
        "\n",
        "\n",
        "\n",
        "#combinação de variaveis \n",
        "#AGRUPANDO RELAÇÃO DE CARGOS COM ESTADO CIVIL\n",
        "dataset_bank %>%\n",
        "  group_by(job, marital) %>%\n",
        "  summarise(n = n())\n",
        "\n",
        "\n",
        "dataset_bank %>%\n",
        "  group_by(job, marital) %>%\n",
        "  summarise(n=n()) %>%\n",
        "  ggplot(aes(x=job, y=n, fill = marital)) +\n",
        "  geom_bar(stat ='identity', position = \"dodge\") +\n",
        "  theme(axis.text.x = element_text(angle=90, hjust = 1))\n",
        "\n",
        "\n",
        "#Criar variaveis dummy para representar essa uniao\n",
        "dmy <- dummyVars( ~ job:marital, data=dataset_bank)\n",
        "bank_cross <- predict(dmy, newdata = dataset_bank)\n",
        "View(bank_cross)"
      ],
      "execution_count": null,
      "outputs": []
    }
  ]
}